[package]
name = "nullhawk-browser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nullhawk-types.workspace = true
nullhawk-http.workspace = true
nullhawk-engine.workspace = true
tokio = { workspace = true, features = ["time"] }
serde = { workspace = true }
serde_json.workspace = true
base64.workspace = true
tempfile.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[[example]]
name = "screenshot"
path = "examples/screenshot.rs"

[[example]]
name = "capture"
path = "examples/capture.rs"
